
const posts = [
    {
        id: 1,
        title: 'Brunch this week?',
        text: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        profileImage : 'https://organicthemes.com/demo/profile/files/2018/05/profile-pic.jpg'
    },
    {
        id: 2,
        title: 'Birthday Gift',
        text: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        profileImage : 'https://organicthemes.com/demo/profile/files/2018/05/profile-pic.jpg'
    },
    {
        id: 3,
        title: 'Recipe to try',
        text: 'I am try out this new BBQ recipe, I think this might be amazing',
        profileImage : 'https://organicthemes.com/demo/profile/files/2018/05/profile-pic.jpg'
    },
    {
        id: 4,
        title: 'Yes!',
        text: 'I have the tickets to the ReactConf for this year.',
        profileImage : 'https://organicthemes.com/demo/profile/files/2018/05/profile-pic.jpg'
    },
    {
        id: 5,
        title: "Doctor's Appointment",
        text: 'My appointment for the doctor was rescheduled for next Saturday.',
        profileImage : 'https://organicthemes.com/demo/profile/files/2018/05/profile-pic.jpg'
    },
    {
        id: 6,
        title: 'Discussion',
        text: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        profileImage : 'https://organicthemes.com/demo/profile/files/2018/05/profile-pic.jpg'
    },
    {
        id: 7,
        title: 'Summer BBQ',
        text: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        profileImage : 'https://organicthemes.com/demo/profile/files/2018/05/profile-pic.jpg'
    },
];
export default posts
